version: "3.9"

services:
  music-go-app:
    container_name: music-go-app
    build:
      context: .
      dockerfile: ./Dockerfile
    env_file:
      - .env
    ports:
      - "8050:8050/tcp"
    networks:
      - default

networks:
  default:
    name: network
    driver: bridge

volumes:
  db:
    driver: local
