name: Go

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

jobs:
  push_to_registry:
    name: Push Docker image to Oracle Container Registry
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repo
        uses: actions/checkout@v3
        with:
          context: .
      - uses: docker-practice/actions-setup-docker@master
        timeout-minutes: 12
      - run: |
          set -x
          docker login ${{secrets.REGION_KEY}} -u "${{secrets.USER}}" -p "${{secrets.TOKEN}}"
          docker version
          docker build -t music-collection-app .
          docker tag music-collection-api:latest ${{secrets.REGION_KEY}}/${{secrets.TENANCY}}/music-collection-app:latest
          docker push ${{secrets.REGION_KEY}}/${{secrets.TENANCY}}/music-collection-app:latest
