# name: Go

# on:
#   push:
#     branches:
#       - main

#   pull_request:
#     branches:
#       - main

# jobs:
#   push_to_registry:
#     name: Push Docker image to Oracle Container Registry
#     runs-on: ubuntu-latest
#     steps:
#       - name: Check out the repo
#         uses: actions/checkout@v3
      
#       - name: Login to Oracle Container Registry
#         uses: docker/login-action@v2
#         with:
#           registry: gru.ocir.io
#           username: ${{ secrets.USER }}
#           password: ${{ secrets.TOKEN }}
          
#       - name: Build and push Docker image
#         uses: docker/build-push-action@3b5e8027fcad23fda98b2e3ac259d8d67585f671
#         with:
#           context: .
#           file: ./Dockerfile
#           push: true
#           tags: ${{secrets.REGION_KEY}}/${{secrets.TENANCY}}/music-collection-app:latest
